name: hotel_stream
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  video_player: ^2.9.3
  chewie: ^1.4.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  path_provider: ^2.1.1
  network_info_plus: ^4.1.0
  url_launcher: ^6.2.4
  flutter_lock_task: ^0.0.2
  better_player: ^0.0.84
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_translation: ^0.20.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/ic_new-playstore.png
    - assets/images/
    - assets/json/
    - assets/videos/intro.mp4